# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'abrevva-ios-sdk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CocoaMQTT'
  pod 'abrevva-ios-sdk', :path => '../'
  # Pods for abrevva-ios-sdk

  target 'abrevva-ios-sdkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'abrevva-ios-sdkUITests' do
    # Pods for testing
  end

end


